apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubedb-mongodb-global
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.alert.ruleSelector }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  groups:
    - name: mongodb.rules
      rules:
      {{- if .Values.alert.rules.mongodbDown.enabled }}
      - alert: MongodbDown
        annotations:
          description: "MongoDB instace is down\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
          summary: MongoDB Down (instance {{`{{`}} $labels.instance {{`}}`}})
        expr: sum(mongodb_up) by (job,namespace) < {{ .Values.alert.rules.mongodbDown.numberOfMembers }}
        for: {{ .Values.alert.rules.mongodbDown.duration }}
        labels:
          alertname: mongodb_down
          app: mongodb
          severity: {{ .Values.alert.rules.mongodbDown.severity }}
      {{- end }}
