metadata:
  resource:
    group: kubedb.com
    kind: MariaDB
    name: mariadbs
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""

form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: true

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: true
        rules:
          mySQLInstanceDown:
            enabled: true
            duration: "0m"
            severity: critical
          mySQLServiceDown:
            enabled: true
            duration: "0m"
            severity: critical
          mySQLTooManyConnections:
            enabled: true
            duration: "2m"
            val: 80
            severity: warning
          mySQLHighThreadsRunning:
            enabled: true
            duration: "2m"
            val: 60
            severity: warning
          mySQLSlowQueries:
            enabled: true
            duration: "2m"
            severity: warning
          mySQLInnoDBLogWaits:
            enabled: true
            duration: "0m"
            val: 10
            severity: warning
          mySQLRestarted:
            enabled: true
            duration: "0m"
            val: 60
            severity: warning
          mySQLHighQPS:
            enabled: true
            duration: "0m"
            val: 1000
            severity: critical
          mySQLHighIncomingBytes:
            enabled: true
            duration: "0m"
            val: 1048576 # 1MB
            severity: critical
          mySQLHighOutgoingBytes:
            enabled: true
            duration: "0m"
            val: 1048576 # 1MB
            severity: critical
          mySQLTooManyOpenFiles:
            enabled: true
            duration: "2m"
            val: 80
            severity: warning
      cluster:
        enabled: true
        rules:
          galeraReplicationLatencyTooLong:
            enabled: true
            val: 0.1
            duration: "5m"
            severity: warning
      provisioner:
        enabled: true
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning
      opsManager:
        enabled: true
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical
      stash:
        enabled: true
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: warning
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
      schemaManager:
        enabled: true
        rules:
          schemaPendingForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaInProgressForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaTerminatingForTooLong:
            enabled: true
            duration: "30m"
            severity: warning
          schemaFailed:
            enabled: true
            duration: "0m"
            severity: warning
          schemaExpired:
            enabled: true
            duration: "0m"
            severity: warning
