properties:
  form:
    properties:
      alert:
        properties:
          additionalRuleLabels:
            additionalProperties:
              type: string
            type: object
          annotations:
            additionalProperties:
              type: string
            type: object
          enabled:
            enum:
            - none
            - critical
            - warning
            - info
            type: string
          groups:
            properties:
              database:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      connectClusterPhaseCritical:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      connectClusterTooManyConnections:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      connectClusterWorkerDown:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      connectclusterConnectorCount:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      connectclusterCoordinatorRebalanceFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      connectclusterTaskTotal:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      connectclusterTaskTotalDestroyed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      connectclusterTaskTotalFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      connectclusterTasksErrorTotalRetries:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - connectClusterPhaseCritical
                    - connectClusterTooManyConnections
                    - connectClusterWorkerDown
                    - connectclusterConnectorCount
                    - connectclusterCoordinatorRebalanceFailed
                    - connectclusterTaskTotal
                    - connectclusterTaskTotalDestroyed
                    - connectclusterTaskTotalFailed
                    - connectclusterTasksErrorTotalRetries
                    type: object
                required:
                - enabled
                - rules
                type: object
              provisioner:
                properties:
                  enabled:
                    enum:
                    - none
                    - critical
                    - warning
                    - info
                    type: string
                  rules:
                    properties:
                      appPhaseCritical:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      appPhaseNotReady:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            enum:
                            - critical
                            - warning
                            - info
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - appPhaseCritical
                    - appPhaseNotReady
                    type: object
                required:
                - enabled
                - rules
                type: object
            required:
            - database
            - provisioner
            type: object
          labels:
            additionalProperties:
              type: string
            type: object
        required:
        - enabled
        - groups
        - labels
        type: object
    required:
    - alert
    type: object
  grafana:
    properties:
      apikey:
        type: string
      enabled:
        type: boolean
      jobName:
        type: string
      url:
        type: string
      version:
        type: string
    required:
    - apikey
    - enabled
    - jobName
    - url
    - version
    type: object
  metadata:
    properties:
      release:
        properties:
          name:
            type: string
          namespace:
            type: string
        required:
        - name
        - namespace
        type: object
      resource:
        description: ResourceID identifies a resource
        properties:
          group:
            type: string
          kind:
            description: Kind is the serialized kind of the resource.  It is normally
              CamelCase and singular.
            type: string
          name:
            description: 'Name is the plural name of the resource to serve.  It must
              match the name of the CustomResourceDefinition-registration too: plural.group
              and it must be all lowercase.'
            type: string
          scope:
            description: ResourceScope is an enum defining the different scopes available
              to a custom resource
            type: string
          version:
            type: string
        required:
        - group
        type: object
    required:
    - release
    - resource
    type: object
required:
- form
- grafana
type: object
