apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 32.2.1
    chart: kube-prometheus-stack-32.2.1
    heritage: Helm
    release: prometheus
  name: kubedb-postgres-summary-alerts
  namespace: monitoring
spec:
  groups:
    - name: postgres.rules
      rules:
        - alert: KubeDBPostgreSQLPhaseNotReady
          expr: kubedb_postgres_status_phase{phase="NotReady"} == 1
          for: 1s
          labels:
            severity: critical
          annotations:
            summary: KubeDB PostgreSQL Phase NotReady (postgres {{ $labels.postgres}})
            description: "KubeDB PostgreSQL Phase not ready on {{ $labels.postgres }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: KubeDBPostgreSQLPhaseCritical
          expr: kubedb_postgres_status_phase{phase="Critical"} == 1
          for: 0s
          labels:
            severity: warning
          annotations:
            summary: KubeDB PostgreSQL Phase Critical (postgres {{ $labels.postgres}})
            description: "KubeDB PostgreSQL Phase not ready on {{ $labels.postgres }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"