metadata:
  resource:
    group: kubedb.com
    kind: RabbitMQ
    name: rabbitmqs
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""
form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: prometheus

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          rabbitmqPhaseCritical:
            enabled: true
            duration: "3m"
            severity: warning
          # Sepcifies the alert configuration for database is in NotReady phase, that means the database is not accepting connections, read/write are hampered.
          rabbitmqDown:
            enabled: true
            duration: "30s"
            severity: critical
          # Sepcifies the alert configuration for high latency.
          rabbitmqFileDescriptorsNearLimit:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqHighConnectionChurn:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqInsufficientEstablishedErlangDistributionLinks:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqLowDiskWatermarkPredicted:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqUnroutableMessages:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqTCPSocketsNearLimit:
            enabled: true
            duration: "30s"
            severity: warning
          rabbitmqQueueIsGrowing:
            enabled: true
            duration: "30s"
            severity: warning
      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

grafana:
  enabled: true
  version: 8.2.3
  jobName: kubedb-databases
  url: "http://prometheus-grafana.monitoring.svc:80"
  apikey: "eyJrIjoiOFdnY3pYWjNkUDRPaUMydDNRUXNMeVAydHNkOXFpd2YiLCJuIjoic2RzZCIsImlkIjoxfQ=="
