apiVersion: v2
name: vaultserver
description: A Helm chart for VaultServer Alert by AppsCode
type: application
version: v0.1.0
appVersion: v0.1.0
home: https://github.com/appscode/alerts
icon: https://cdn.appscode.com/images/products/kubevault/kubevault-icon.png
sources:
  - https://github.com/appscode/alerts
maintainers:
  - name: appscode
    email: support@appscode.com
