metadata:
  resource:
    group: kubevault.com
    kind: VaultServer
    name: vaultserver
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""

form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: true

    ## Labels for default rules
    labels: # +doc-gen:break
      release: prometheus

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      vault:
        enabled: true
        rules:
          vaultDown:
            enabled: true
            duration: "0m"
            severity: critical
          vaultSealed:
            enabled: true
            duration: "0m"
            severity: critical
          vaultAutoPilotNodeUnhealthy:
            enabled: true
            duration: "1m"
            severity: critical
          vaultLeadershipLoss:
            enabled: true
            duration: "1m"
            val: 5
            severity: critical
          vaultLeadershipStepsDowns:
            enabled: true
            duration: "1m"
            val: 5
            severity: critical
          vaultLeadershipSetupFailures:
            enabled: true
            duration: "1m"
            val: 5
            severity: critical
          vaultRequestFailures:
            enabled: true
            duration: "15m"
            severity: critical
          vaultResponseFailures:
            enabled: true
            duration: "15m"
            severity: critical
          vaultTooManyInfinityTokens:
            enabled: true
            duration: "5m"
            val: 3
            severity: warning
      operator:
        enabled: true
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "5m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning
      opsManager:
        enabled: true
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical
      stash:
        enabled: true
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: warning
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: warning
