namespace: demo
dbName: my-group
alert:
  ruleSelector:
    app: kube-prometheus-stack
    release: prometheus
  groups:
    database:
      enabled: true
      rules:
        mySQLInstanceDown:
          enabled: true
          duration: "0m"
          severity: critical
        mySQLServiceDown:
          enabled: true
          duration: "0m"
          severity: critical
        mySQLTooManyConnections:
          enabled: true
          duration: "2m"
          val: 80
          severity: warning
        mySQLHighThreadsRunning:
          enabled: true
          duration: "2m"
          val: 60
          severity: warning
        mySQLSlowQueries:
          enabled: true
          duration: "2m"
          severity: warning
        mySQLInnoDBLogWaits:
          enabled: true
          duration: "0m"
          val: 10
          severity: warning
        mySQLRestarted:
          enabled: true
          duration: "0m"
          val: 60
          severity: warning
        mySQLHighQPS:
          enabled: true
          duration: "0m"
          val: 1000
          severity: critical
        mySQLHighIncomingBytes:
          enabled: true
          duration: "0m"
          val: 1048576 # 1MB
          severity: critical
        mySQLHighOutgoingBytes:
          enabled: true
          duration: "0m"
          val: 1048576 # 1MB
          severity: critical
        mySQLTooManyOpenFiles:
          enabled: true
          duration: "2m"
          val: 80
          severity: warning
    group:
      enabled: true
      rules:
        mySQLHighReplicationDelay:
          enabled: true
          val: 0.5 # second
          duration: "5m"
          severity: warning
        mySQLHighReplicationTransportTime:
          enabled: true
          val: 0.5 # second
          duration: "5m"
          severity: warning
        mySQLHighReplicationApplyTime:
          enabled: true
          val: 0.5 # second
          duration: "5m"
          severity: warning
        mySQLReplicationHighTransactionTime:
          enabled: true
          val: 0.5 # second
          duration: "5m"
          severity: warning
    kubedb:
      enabled: true
      rules:
        kubeDBMySQLPhaseNotReady:
          enabled: true
          duration: "1m"
          severity: critical
        kubeDBMySQLPhaseCritical:
          enabled: true
          duration: "15m"
          severity: warning
    opsrequest:
      enabled: true
      rules:
        kubeDBMySQLOpsRequestOnProgress:
          enabled: true
          duration: "0m"
          severity: warning
        kubeDBMySQLOpsRequestStatusProgressingToLong:
          enabled: true
          duration: "30m"
          severity: critical
        kubeDBMySQLOpsRequestFailed:
          enabled: true
          duration: "0m"
          severity: critical
    stash:
      enabled: true
      rules:
        mySQLStashBackupSessionFailed:
          enabled: true
          duration: "0m"
          severity: critical
        mySQLStashRestoreSessionFailed:
          enabled: true
          duration: "0m"
          severity: critical
        mySQLStashNoBackupSessionForTooLong:
          enabled: true
          duration: "0m"
          val: 18000
          severity: warning
        mySQLStashRepositoryCorrupted:
          enabled: true
          duration: "5m"
          severity: critical
        mySQLStashRepositoryStorageRunningLow:
          enabled: true
          duration: "5m"
          val: 10737418240 # 10GB
          severity: waring
        mySQLStashBackupSessionPeriodTooLong:
          enabled: true
          duration: "0m"
          val: 1800 # 30 minute
          severity: waring
        mySQLStashRestoreSessionPeriodTooLong:
          enabled: true
          duration: "0m"
          val: 1800 # 30 minute
          severity: waring
    schema:
      enabled: true
      rules:
        kubeDBMySQLSchemaPendingForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBMySQLSchemaInProgressForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBMySQLSchemaTerminatingForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBMySQLSchemaFailed:
          enabled: true
          duration: "0m"
          severity: warning
        kubeDBMySQLSchemaExpired:
          enabled: true
          duration: "0m"
          severity: warning