{{ $app := (include "proxysql.fullname" .) }}

  {{ if .Values.form.alert.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
  {{- if .Values.form.alert.labels }}
  {{- toYaml .Values.form.alert.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.form.alert.annotations }}
annotations:
  {{- toYaml .Values.form.alert.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{ if .Values.form.alert.groups.database.enabled -}}
  - name: proxysql.database.{{ .Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if .Values.form.alert.groups.database.rules.proxysqlSQLInstanceDown.enabled -}}
    - alert: ProxySQLInstanceDown
      expr: proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"} == 0
      for: {{ .Values.form.alert.groups.database.rules.proxySQLInstanceDown.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLInstanceDown.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLServiceDown.enabled -}}
    - alert: ProxySQLServiceDown
      expr: sum by (service) (proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}) == 0
      for: {{ .Values.form.alert.groups.database.rules.proxySQLServiceDown.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLServiceDown.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL service down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL service is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLTooManyConnections.enabled -}}
    - alert: ProxySQLTooManyConnections
      expr: max_over_time(proxysql_client_connections_connected{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m]) / proxysql_mysql_max_connections{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"} * 100 > {{.Values.form.alert.groups.database.rules.proxySQLTooManyConnections.val}}
      for: {{ .Values.form.alert.groups.database.rules.proxySQLTooManyConnections.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLTooManyConnections.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL too many connections (> {{.Values.form.alert.groups.database.rules.proxySQLTooManyConnections.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "More than {{.Values.form.alert.groups.database.rules.proxySQLTooManyConnections.val}}% of ProxySQL connections are in use on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
#    {{ if .Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.enabled -}}
#    - alert: ProxySQLHighThreadsRunning
#      expr: max_over_time(mysql_global_status_threads_running{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m]) / mysql_global_variables_max_connections{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"} * 100 > {{.Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.val}}
#      for: {{ .Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.duration }}
#      labels:
#        severity: {{ .Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.severity }}
#        {{- include "proxysql.alertLabels" . | nindent 8 }}
#      annotations:
#        summary: ProxySQL high threads running (> {{.Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
#        description: "More than {{.Values.form.alert.groups.database.rules.proxySQLHighThreadsRunning.val}}% of ProxySQL threads are in use on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
#    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLSlowQueries.enabled -}}
    - alert: ProxySQLSlowQueries
      expr: increase(proxysql_slow_queries_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m]) > 0
      for: {{ .Values.form.alert.groups.database.rules.proxySQLSlowQueries.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLSlowQueries.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL slow queries on (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL server mysql has some new slow query.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
#    {{ if .Values.form.alert.groups.database.rules.proxySQLInnoDBLogWaits.enabled -}}
#    - alert: ProxySQLInnoDBLogWaits
#      expr: rate(mysql_global_status_innodb_log_waits{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[15m]) > {{.Values.form.alert.groups.database.rules.proxySQLInnoDBLogWaits.val}}
#      for: {{ .Values.form.alert.groups.database.rules.proxySQLInnoDBLogWaits.duration }}
#      labels:
#        severity: {{ .Values.form.alert.groups.database.rules.proxySQLInnoDBLogWaits.severity }}
#        {{- include "proxysql.alertLabels" . | nindent 8 }}
#      annotations:
#        summary: ProxySQL InnoDB log waits (> {{.Values.form.alert.groups.database.rules.proxySQLInnoDBLogWaits.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
#        description: "ProxySQL innodb log writes stalling\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
#    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLRestarted.enabled -}}
    - alert: ProxySQLRestarted
      expr: proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"} < {{.Values.form.alert.groups.database.rules.proxySQLRestarted.val}}
      for: {{ .Values.form.alert.groups.database.rules.proxySQLRestarted.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLRestarted.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL restarted ({{.Values.form.alert.groups.database.rules.proxySQLRestarted.val}} second ago) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL restarted\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLHighQPS.enabled -}}
    - alert: ProxySQLHighQPS
      expr: rate(mysql_global_status_queries{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m]) > {{.Values.form.alert.groups.database.rules.proxySQLHighQPS.val}}
      for: {{ .Values.form.alert.groups.database.rules.proxySQLHighQPS.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLHighQPS.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL has high queries per second (> {{.Values.form.alert.groups.database.rules.proxySQLHighQPS.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL has high QPS on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLHighIncomingBytes.enabled -}}
    - alert: ProxySQLHighIncomingBytes
      expr: rate(proxysql_queries_frontends_bytes_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}",traffic_flow="received"}[1m]) > {{.Values.form.alert.groups.database.rules.proxySQLHighIncomingBytes.val}}
      for: {{ .Values.form.alert.groups.database.rules.proxySQLHighIncomingBytes.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLHighIncomingBytes.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL has high incoming bytes second (> {{.Values.form.alert.groups.database.rules.proxySQLHighIncomingBytes.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL has high incoming bytes per second on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.database.rules.proxySQLHighOutgoingBytes.enabled -}}
    - alert: ProxySQLHighOutgoingBytes
      expr: rate(proxysql_queries_frontends_bytes_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}",traffic_flow="sent"}[1m]) > {{.Values.form.alert.groups.database.rules.proxySQLHighOutgoingBytes.val}}
      for: {{ .Values.form.alert.groups.database.rules.proxySQLHighOutgoingBytes.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.database.rules.proxySQLHighOutgoingBytes.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL has high outgoing bytes second (> {{.Values.form.alert.groups.database.rules.proxySQLHighOutgoingBytes.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL has high outgoing bytes per second on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
#    {{ if .Values.form.alert.groups.database.rules.proxySQLTooManyOpenFiles.enabled -}}
#    - alert: ProxySQLTooManyOpenFiles
#      expr: max_over_time(mysql_global_status_open_files{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m]) / mysql_global_variables_open_files_limit{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"} * 100 > {{.Values.form.alert.groups.database.rules.proxySQLTooManyOpenFiles.val}}
#      for: {{ .Values.form.alert.groups.database.rules.proxySQLTooManyOpenFiles.duration }}
#      labels:
#        severity: {{ .Values.form.alert.groups.database.rules.proxySQLTooManyOpenFiles.severity }}
#        {{- include "proxysql.alertLabels" . | nindent 8 }}
#      annotations:
#        summary: ProxySQL too many opened files (> {{.Values.form.alert.groups.database.rules.proxySQLTooManyOpenFiles.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
#        description: "ProxySQL too many opened files on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
#    {{- end }}
  {{ end -}}
  {{ if .Values.form.alert.groups.cluster.enabled -}}
  - name: proxysql.cluster.{{ .Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if .Values.form.alert.groups.cluster.rules.proxysqlCLusterSyncFailure.enabled -}}
    - alert: GaleraReplicationLatencyTooLong
      expr: sum by(job) (rate(proxysql_cluster_syn_conflict_total{job="{{ $app }}-stats",namespace="{{ .Release.Namespace }}"}[1m])) > {{.Values.form.alert.groups.cluster.rules.proxysqlCLusterSyncFailure.val}}
      for: {{ .Values.form.alert.groups.cluster.rules.proxysqlCLusterSyncFailure.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.cluster.rules.proxysqlCLusterSyncFailure.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQL Galera Cluster latency too long ( > {{.Values.form.alert.groups.cluster.rules.proxysqlCLusterSyncFailure.val}} second,) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL Cluster Sync Failed for {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ if .Values.form.alert.groups.provisioner.enabled -}}
  - name: proxysql.provisioner.{{ .Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if .Values.form.alert.groups.provisioner.rules.appPhaseNotReady.enabled -}}
    - alert: KubeDBProxySQLPhaseNotReady
      expr: kubedb_com_proxysql_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ .Release.Namespace }}"} == 1
      for: {{ .Values.form.alert.groups.provisioner.rules.appPhaseNotReady.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.provisioner.rules.appPhaseNotReady.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: KubeDB ProxySQL Phase NotReady (proxysql {{`{{`}} $labels.proxysql {{`}}`}})
        description: "KubeDB ProxySQL Phase not ready on {{`{{`}} $labels.proxysql {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.provisioner.rules.appPhaseCritical.enabled -}}
    - alert: KubeDBProxySQLPhaseCritical
      expr: kubedb_com_proxysql_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ .Release.Namespace }}"} == 1
      for: {{ .Values.form.alert.groups.provisioner.rules.appPhaseCritical.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.provisioner.rules.appPhaseCritical.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: KubeDB ProxySQL Phase Critical (proxysql {{`{{`}} $labels.proxysql {{`}}`}})
        description: "KubeDB ProxySQL Phase Critical {{`{{`}} $labels.proxysql {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ if .Values.form.alert.groups.opsManager.enabled -}}
  - name: proxysql.opsManager.{{ .Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if .Values.form.alert.groups.opsManager.rules.opsRequestOnProgress.enabled -}}
    - alert: KubeDBProxySQLOpsRequestOnProgress
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ .Release.Namespace }}"} == 1
      for: {{ .Values.form.alert.groups.opsManager.rules.opsRequestOnProgress.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.opsManager.rules.opsRequestOnProgress.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest on progress (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "MaraiDBOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} is in progressressing status\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.opsManager.rules.opsRequestStatusProgressingToLong.enabled -}}
    - alert: KubeDBProxySQLOpsRequestStatusProgressingToLong
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ .Release.Namespace }}"} == 1
      for: {{ .Values.form.alert.groups.opsManager.rules.opsRequestStatusProgressingToLong.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.opsManager.rules.opsRequestStatusProgressingToLong.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest is in progressing status for too long (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "MaraiDBOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} is in progressing status for too long\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if .Values.form.alert.groups.opsManager.rules.opsRequestFailed.enabled -}}
    - alert: KubeDBProxySQLOpsRequestFailed
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Failed",app="{{ $app }}",namespace="{{ .Release.Namespace }}"} == 1
      for: {{ .Values.form.alert.groups.opsManager.rules.opsRequestFailed.duration }}
      labels:
        severity: {{ .Values.form.alert.groups.opsManager.rules.opsRequestFailed.severity }}
        {{- include "proxysql.alertLabels" . | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest failed (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "MaraiDBOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} failed \n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end }}
