apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 32.2.1
    chart: kube-prometheus-stack-32.2.1
    heritage: Helm
    release: prometheus
  name: kubedb-mariadb-database-alerts
  namespace: monitoring
spec:
  groups:
  - name: mariadb.rules
    rules:
    - alert: GaleraClusterReplicationLatencyTooLong
      expr: mysql_galera_evs_repl_latency_avg_seconds > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: MariaDB Galera Cluster latency too long ( > 100 ms) (instance {{ $labels.pod }})
        description: "MariaDB Galera Cluster latency too long ( > 100 ms) on {{ $labels.pod }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      
