apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 32.2.1
    chart: kube-prometheus-stack-32.2.1
    heritage: Helm
    release: prometheus
  name: kubedb-mariadb-opsrequest-alerts
  namespace: monitoring
spec:
  groups:
  - name: mariadb.rules
    rules:
    - alert: KubeDBMariaDBOpsRequestOnProgress
      expr: kubedb_mariadb_opsrequest_status_phase{phase='Progressing'} == 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: MariaDBOpsRequest on progress (mariadbopsrequest {{ $labels.mariadbopsrequest}})
        description: "MaraiDBOpsRequest {{ $labels.mariadbopsrequest }} is in progressressing status\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubeDBMariaDBOpsRequestStatusProgressingToLong
      expr: kubedb_mariadb_opsrequest_status_phase{phase='Progressing'} == 1
      for: 30m
      labels:
        severity: critical
      annotations:
        summary: MariaDBOpsRequest is in progressing status for too long (mariadbopsrequest {{ $labels.mariadbopsrequest}})
        description: "MaraiDBOpsRequest {{ $labels.mariadbopsrequest }} is in progressing status for too long\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubeDBMariaDBOpsRequestFailed
      expr: kubedb_mariadb_opsrequest_status_phase{phase='Failed'} == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MariaDBOpsRequest failed (mariadbopsrequest {{ $labels.mariadbopsrequest}})
        description: "MaraiDBOpsRequest {{ $labels.mariadbopsrequest }} failed status\n VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    