metadata:
  resource:
    group: kubedb.com
    kind: Druid
    name: druids
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: "druid-sample"
    # Release namespace
    namespace: "druid"
form:
  alert:
    ## Enable PrometheusRule alerts
    enabled: warning

    ## Labels for default rules
    labels: # +doc-gen:break
      release: prometheus

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: warning
        rules:
          druidDown:
            enabled: true
            duration: "30s"
            severity: critical
          zkDisconnected:
            enabled: true
            duration: "30s"
            severity: critical
          highQueryTime:
            enabled: true
            duration: "1m"
            severity: warning
          highQueryWaitTime:
            enabled: true
            duration: "1m"
            severity: warning
          highSegmentScanPending:
            enabled: true
            duration: "1m"
            severity: "warning"
            val: 2
          highSegmentUsage:
            enabled: true
            duration: "1m"
            severity: "critical"
            val: 95
          highJVMPoolUsage:
            enabled: true
            duration: "30s"
            severity: "warning"
            val: 95
          highJVMMemoryUsage:
            enabled: true
            duration: "30s"
            severity: "warning"
            val: 95
      provisioner:
        enabled: warning
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning

grafana:
  enabled: true
  version: 8.2.3
  jobName: kubedb-databases
  url: ""
  apikey: ""