namespace: demo
dbName: sample-postgres
alert:
  ruleSelector:
    app: kube-prometheus-stack
    release: prometheus
  groups:
    database:
      enabled: true
      rules:
        postgresInstanceDown:
          enabled: true
          duration: "0m"
          severity: critical
        postgresRestarted:
          enabled: true
          duration: "0m"
          severity: critical
        postgresTooManyConnections:
          enabled: true
          duration: "2m"
          val: 80
          severity: warning
        postgresqlNotEnoughConnections:
          enabled: true
          duration: "2m"
          val: 5
          severity: warning
        postgresSlowQueries:
          enabled: true
          duration: "2m"
          severity: warning
        postgresqlReplicationLag:
          enabled: true
          duration: "0m"
          val: 30s
          severity: critical
        postgresqlHighRollbackRate:
          enabled: true
          duration: "0m"
          val: 0.02
          severity: warning
        postgresqlSplitBrain:
          enabled: true
          duration: "0m"
          severity: critical
        postgresqlTooManyLocksAcquired:
          enabled: true
          duration: "2m"
          val: 0.20
          severity: critical
    kubedb:
      enabled: true
      rules:
        kubeDBPostgresPhaseNotReady:
          enabled: true
          duration: "1m"
          severity: critical
        kubeDBPostgresPhaseCritical:
          enabled: true
          duration: "15m"
          severity: warning
    opsrequest:
      enabled: true
      rules:
        kubeDBPostgresOpsRequestOnProgress:
          enabled: true
          duration: "0m"
          severity: warning
        kubeDBPostgresOpsRequestStatusProgressingToLong:
          enabled: true
          duration: "30m"
          severity: critical
        kubeDBPostgresOpsRequestFailed:
          enabled: true
          duration: "0m"
          severity: critical
    stash:
      enabled: true
      rules:
        postgresStashBackupSessionFailed:
          enabled: true
          duration: "0m"
          severity: critical
        postgresStashRestoreSessionFailed:
          enabled: true
          duration: "0m"
          severity: critical
        postgresStashNoBackupSessionForTooLong:
          enabled: true
          duration: "0m"
          val: 18000
          severity: warning
        postgresStashRepositoryCorrupted:
          enabled: true
          duration: "5m"
          severity: critical
        postgresStashRepositoryStorageRunningLow:
          enabled: true
          duration: "5m"
          val: 10737418240 # 10GB
          severity: waring
    schema:
      enabled: true
      rules:
        kubeDBPostgresSchemaPendingForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBPostgresSchemaInProgressForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBPostgresSchemaTerminatingForTooLong:
          enabled: true
          duration: "30m"
          severity: warning
        kubeDBPostgresSchemaFailed:
          enabled: true
          duration: "0m"
          severity: warning
        kubeDBPostgresSchemaExpired:
          enabled: true
          duration: "0m"
          severity: warning
