properties:
  form:
    properties:
      alert:
        properties:
          additionalRuleLabels:
            additionalProperties:
              type: string
            type: object
          annotations:
            additionalProperties:
              type: string
            type: object
          enabled:
            type: boolean
          groups:
            properties:
              database:
                properties:
                  enabled:
                    type: boolean
                  rules:
                    properties:
                      postgresInstanceDown:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      postgresRestarted:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      postgresSlowQueries:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      postgresTooManyConnections:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      postgresqlHighRollbackRate:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            format: double
                            type: number
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      postgresqlNotEnoughConnections:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      postgresqlReplicationLag:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      postgresqlSplitBrain:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      postgresqlTooManyLocksAcquired:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            format: double
                            type: number
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - postgresInstanceDown
                    - postgresRestarted
                    - postgresSlowQueries
                    - postgresTooManyConnections
                    - postgresqlHighRollbackRate
                    - postgresqlNotEnoughConnections
                    - postgresqlReplicationLag
                    - postgresqlSplitBrain
                    - postgresqlTooManyLocksAcquired
                    type: object
                required:
                - enabled
                - rules
                type: object
              opsManager:
                properties:
                  enabled:
                    type: boolean
                  rules:
                    properties:
                      opsRequestFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      opsRequestOnProgress:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      opsRequestStatusProgressingToLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - opsRequestFailed
                    - opsRequestOnProgress
                    - opsRequestStatusProgressingToLong
                    type: object
                required:
                - enabled
                - rules
                type: object
              provisioner:
                properties:
                  enabled:
                    type: boolean
                  rules:
                    properties:
                      appPhaseCritical:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      appPhaseNotReady:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - appPhaseCritical
                    - appPhaseNotReady
                    type: object
                required:
                - enabled
                - rules
                type: object
              schemaManager:
                properties:
                  enabled:
                    type: boolean
                  rules:
                    properties:
                      schemaExpired:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      schemaFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      schemaInProgressForTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      schemaPendingForTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      schemaTerminatingForTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                    required:
                    - schemaExpired
                    - schemaFailed
                    - schemaInProgressForTooLong
                    - schemaPendingForTooLong
                    - schemaTerminatingForTooLong
                    type: object
                required:
                - enabled
                - rules
                type: object
              stash:
                properties:
                  enabled:
                    type: boolean
                  rules:
                    properties:
                      backupSessionFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      backupSessionPeriodTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      noBackupSessionForTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      repositoryCorrupted:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      repositoryStorageRunningLow:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                      restoreSessionFailed:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                        required:
                        - duration
                        - enabled
                        - severity
                        type: object
                      restoreSessionPeriodTooLong:
                        properties:
                          duration:
                            type: string
                          enabled:
                            type: boolean
                          severity:
                            type: string
                          val:
                            type: integer
                        required:
                        - duration
                        - enabled
                        - severity
                        - val
                        type: object
                    required:
                    - backupSessionFailed
                    - backupSessionPeriodTooLong
                    - noBackupSessionForTooLong
                    - repositoryCorrupted
                    - repositoryStorageRunningLow
                    - restoreSessionFailed
                    - restoreSessionPeriodTooLong
                    type: object
                required:
                - enabled
                - rules
                type: object
            required:
            - database
            - opsManager
            - provisioner
            - schemaManager
            - stash
            type: object
          labels:
            additionalProperties:
              type: string
            type: object
        required:
        - additionalRuleLabels
        - annotations
        - enabled
        - groups
        - labels
        type: object
    required:
    - alert
    type: object
  metadata:
    properties:
      release:
        properties:
          name:
            type: string
          namespace:
            type: string
        required:
        - name
        - namespace
        type: object
      resource:
        description: ResourceID identifies a resource
        properties:
          group:
            type: string
          kind:
            description: Kind is the serialized kind of the resource.  It is normally
              CamelCase and singular.
            type: string
          name:
            description: 'Name is the plural name of the resource to serve.  It must
              match the name of the CustomResourceDefinition-registration too: plural.group
              and it must be all lowercase.'
            type: string
          scope:
            description: ResourceScope is an enum defining the different scopes available
              to a custom resource
            type: string
          version:
            type: string
        required:
        - group
        - kind
        - name
        - scope
        - version
        type: object
    required:
    - release
    - resource
    type: object
required:
- form
type: object
