apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 32.2.1
    chart: kube-prometheus-stack-32.2.1
    heritage: Helm
    release: prometheus
  name: kubedb-mariadb-summary-alerts
  namespace: monitoring
spec:
  groups:
  - name: mariadb.rules
    rules:
    - alert: MariaDBStashBackupSessionFailed
      expr: stash_backup_session_success == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MariaDB Stash backup session failed (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash backupsession failed (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashRestoreSessionFailed
      expr: stash_restore_session_success == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MariaDB Stash restore session failed (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash backupsession failed (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashNoBackupSessionForTooLong
      expr: time() - stash_backup_last_success_time_seconds > 18000
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: MariaDB Stash no backup for last 5 hours (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash no backup for last 5 hours (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashRepositoryCorrupted
      expr: stash_repository_integrity == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: MariaDB Stash repository corrupted (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash repository corrupted (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashRepositoryStorageRunningLow
      expr: stash_repository_size_bytes > 10737418240
      for: 5m
      labels:
        severity: waring
      annotations:
        summary: MariaDB Stash Repository storage more than 10 GB (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash Repository storage more than 10 GB (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashBackupSessionPeriodTooLong
      expr: stash_backup_session_duration_seconds > 1800
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: MariaDB Stash backup session taking more than 30 minutes to complete (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash backup session taking more than 30 minutes to complete (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: MariaDBStashRestoreSessionPeriodTooLong
      expr: stash_restore_session_duration_seconds > 1800
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: MariaDB Stash restore session taking more than 30 minutes to complete (invoker_name {{ $labels.invoker_name}})
        description: "MariaDB Stash restore session taking more than 30 minutes to complete (invoker_name {{ $labels.invoker_name}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    
    


# stash_backup_session_success * on(invoker_name, invoker_kind) group_left(target_name, target_kind) stash_backupconfiguration_info{target_name=~"sample-mariadb", target_kind=~"AppBinding", namespace=~"demo"}
# stash_restore_session_success * on(invoker_name, invoker_kind) group_left(target_name, target_kind) stash_restoresession_info{target_name=~"sample-mariadb", target_kind=~"AppBinding", namespace=~"demo"}