metadata:
  resource:
    group: kubedb.com
    kind: Redis
    name: redises
    scope: Namespaced
    version: v1alpha2
  release:
    # Release name
    name: ""
    # Release namespace
    namespace: ""

spec:
  alert:
    ## Enable PrometheusRule alerts
    enabled: true

    ## Labels for default rules
    labels: # +doc-gen:break
      release: kube-prometheus-stack

    ## Annotations for default rules
    annotations: {}

    ## Additional labels for PrometheusRule alerts
    additionalRuleLabels: {}

    ## Prefix for runbook URLs. Use this to override the first part of the runbookURLs that is common to all rules.
    # runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

    groups:
      database:
        enabled: true
        rules:
          redisInstanceDown:
            enabled: true
            duration: "0m"
            severity: critical
          redisRestarted:
            enabled: true
            duration: "0m"
            severity: critical
          redisTooManyConnections:
            enabled: true
            duration: "2m"
            val: 80
            severity: warning
          redisqlNotEnoughConnections:
            enabled: true
            duration: "2m"
            val: 5
            severity: warning
          redisSlowQueries:
            enabled: true
            duration: "2m"
            severity: warning
          redisqlReplicationLag:
            enabled: true
            duration: "0m"
            val: 30s
            severity: critical
          redisqlHighRollbackRate:
            enabled: true
            duration: "0m"
            val: 0.02
            severity: warning
          redisqlSplitBrain:
            enabled: true
            duration: "0m"
            severity: critical
          redisqlTooManyLocksAcquired:
            enabled: true
            duration: "2m"
            val: 0.20
            severity: critical
      provisioner:
        enabled: true
        rules:
          appPhaseNotReady:
            enabled: true
            duration: "1m"
            severity: critical
          appPhaseCritical:
            enabled: true
            duration: "15m"
            severity: warning
      opsManager:
        enabled: true
        rules:
          opsRequestOnProgress:
            enabled: true
            duration: "0m"
            severity: info
          opsRequestStatusProgressingToLong:
            enabled: true
            duration: "30m"
            severity: critical
          opsRequestFailed:
            enabled: true
            duration: "0m"
            severity: critical
      stash:
        enabled: true
        rules:
          backupSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          restoreSessionFailed:
            enabled: true
            duration: "0m"
            severity: critical
          noBackupSessionForTooLong:
            enabled: true
            duration: "0m"
            val: 18000
            severity: warning
          repositoryCorrupted:
            enabled: true
            duration: "5m"
            severity: critical
          repositoryStorageRunningLow:
            enabled: true
            duration: "5m"
            val: 10737418240 # 10GB
            severity: waring
          backupSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: waring
          restoreSessionPeriodTooLong:
            enabled: true
            duration: "0m"
            val: 1800 # 30 minute
            severity: waring
